steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/mcp/Dockerfile
      - -t
      - ${_MCP_IMAGE}
      - .
images:
  - ${_MCP_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
